steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/app:${BUILD_ID}'
      - '-t'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/app:latest'
      - '.'

  # Artifact Registry에 푸시 (BUILD_ID 태그)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/app:${BUILD_ID}'

  # Artifact Registry에 푸시 (latest 태그)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/app:latest'

  # Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cleaners-ai'
      - '--image'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/app:latest'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'

images:
  - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/app:${BUILD_ID}'
  - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
