steps:
  # ============== BACKEND BUILD ==============
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/backend:${BUILD_ID}'
      - '-t'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    waitFor: ['build-backend']
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/backend:${BUILD_ID}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-latest'
    waitFor: ['build-backend']
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/backend:latest'

  # ============== FRONTEND BUILD ==============
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/frontend:${BUILD_ID}'
      - '-t'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/frontend:latest'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    waitFor: ['build-frontend']
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/frontend:${BUILD_ID}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-latest'
    waitFor: ['build-frontend']
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/frontend:latest'

  # Backend URL 조회
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-url'
    waitFor: ['deploy-backend']
    entrypoint: bash
    args:
      - '-c'
      - |
        BACKEND_URL=$$(gcloud run services describe cleaners-ai-backend --region=us-west2 --format='value(status.url)')
        echo "$$BACKEND_URL" > /workspace/backend_url.txt
        echo "Backend URL: $$BACKEND_URL"

  # Frontend 배포 (동적 Backend URL 주입)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'push-frontend-latest', 'get-backend-url']
    entrypoint: bash
    args:
      - '-c'
      - |
        BACKEND_URL=$$(cat /workspace/backend_url.txt)
        gcloud run deploy cleaners-ai-frontend \
          --image us-west2-docker.pkg.dev/askme-482400/cleaners-ai/frontend:latest \
          --region us-west2 \
          --platform managed \
          --allow-unauthenticated \
          --memory 256Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 5 \
          --port 8080 \
          --set-env-vars "BACKEND_URL=$$BACKEND_URL"

images:
  - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/backend:${BUILD_ID}'
  - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/backend:latest'
  - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/frontend:${BUILD_ID}'
  - 'us-west2-docker.pkg.dev/askme-482400/cleaners-ai/frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
